#!/usr/bin/env python3
"""ALink — one-command native deployment for a GCP (Debian/Ubuntu) VM.

Provisions the whole event-driven stack **without Docker**:

  * system packages (Python, Node.js, nginx, RabbitMQ, PostgreSQL, certbot)
  * PostgreSQL role + database
  * RabbitMQ vhost + user
  * backend virtualenv + dependencies (FastAPI, ML, messaging)
  * production ``backend/.env`` (strong JWT secret, CORS, DB + broker URLs)
  * frontend production build (``VITE_API_URL=https://<domain>/api``)
  * nginx site (SPA + ``/api`` and ``/static`` reverse proxy)
  * systemd services: API (gunicorn/uvicorn) + 3 worker microservices
  * HTTPS via Let's Encrypt/certbot

Run it on the VM (needs sudo)::

    sudo python3 run_onVM.py --domain aLink.ahbab.dev --email you@example.com

Idempotent and re-runnable. Useful flags::

    --no-tls        # serve plain HTTP (skip certbot)
    --skip-system   # don't apt-install system packages
    --reset-db      # drop & re-seed the database
    --db sqlite     # use SQLite instead of PostgreSQL
    --branch main   # (informational) the branch you deployed

Prerequisite for TLS: the domain's DNS A record must already point at this
VM's external IP.
"""
from __future__ import annotations

import argparse
import grp
import os
import pwd
import re
import secrets
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

# ─── Paths ──────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent
BACKEND = ROOT / "backend"
FRONTEND = ROOT / "frontend"
VENV = BACKEND / ".venv"
VENV_PY = VENV / "bin" / "python"
VENV_BIN = VENV / "bin"
ENV_FILE = BACKEND / ".env"
DIST = FRONTEND / "dist"

DEFAULT_DOMAIN = "aLink.ahbab.dev"
API_BIND = "127.0.0.1:8000"

SERVICES = ["alink-api", "alink-worker-notifications", "alink-worker-ai", "alink-worker-achievements"]


# ─── Console helpers ────────────────────────────────────────────────────────
def info(msg: str) -> None:
    print(f"\033[1;36m[ALink]\033[0m {msg}", flush=True)


def warn(msg: str) -> None:
    print(f"\033[1;33m[ALink] WARNING:\033[0m {msg}", flush=True)


def die(msg: str) -> None:
    print(f"\033[1;31m[ALink] ERROR:\033[0m {msg}", file=sys.stderr, flush=True)
    raise SystemExit(1)


def run(cmd: list[str], *, check: bool = True, cwd: Path | None = None,
        env: dict | None = None, capture: bool = False, user: str | None = None) -> subprocess.CompletedProcess:
    """Run a command. ``user`` drops privileges (for pip/npm so files aren't root-owned)."""
    if user and user != "root":
        cmd = ["sudo", "-u", user, "-H"] + cmd
    info("$ " + " ".join(cmd))
    return subprocess.run(
        cmd, check=check, cwd=str(cwd) if cwd else None, env=env,
        text=True, capture_output=capture,
    )


def sh(cmd: str, *, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    info("$ " + cmd)
    return subprocess.run(cmd, shell=True, check=check, text=True, capture_output=capture)


# ─── Environment detection ──────────────────────────────────────────────────
def require_root() -> None:
    if os.geteuid() != 0:
        die("Run with sudo:  sudo python3 run_onVM.py --domain <domain> --email <email>")


def deploy_user() -> str:
    """The non-root user that should own files and run the services."""
    sudo_user = os.environ.get("SUDO_USER")
    if sudo_user and sudo_user != "root":
        return sudo_user
    # Fall back to the owner of the repo directory.
    try:
        return pwd.getpwuid(ROOT.stat().st_uid).pw_name
    except KeyError:
        return "root"


def have(cmd: str) -> bool:
    return shutil.which(cmd) is not None


# ─── .env handling ──────────────────────────────────────────────────────────
def read_env() -> dict[str, str]:
    data: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            data[k.strip()] = v.strip()
    return data


def write_env(values: dict[str, str], owner: str) -> None:
    lines = [
        "# Generated by run_onVM.py — production configuration.",
        "environment=production",
    ]
    for key in ("database_url", "rabbitmq_url", "events_exchange", "jwt_secret",
                "jwt_algorithm", "jwt_expires_minutes", "cors_origins",
                "anthropic_api_key", "anthropic_model"):
        if values.get(key):
            lines.append(f"{key}={values[key]}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    chown(ENV_FILE, owner)
    os.chmod(ENV_FILE, 0o600)
    info(f"Wrote {ENV_FILE}")


def chown(path: Path, owner: str) -> None:
    try:
        uid = pwd.getpwnam(owner).pw_uid
        gid = pwd.getpwnam(owner).pw_gid
        os.chown(path, uid, gid)
    except (KeyError, PermissionError):
        pass


# ─── System packages ────────────────────────────────────────────────────────
def install_system(args) -> None:
    if args.skip_system:
        info("Skipping system package installation (--skip-system).")
        return
    info("Installing system packages (apt)…")
    os.environ["DEBIAN_FRONTEND"] = "noninteractive"
    sh("apt-get update -y")
    base = [
        "python3", "python3-venv", "python3-dev", "build-essential",
        "nginx", "rabbitmq-server", "git", "curl", "ca-certificates",
    ]
    if args.db == "postgres":
        base += ["postgresql", "postgresql-contrib", "libpq-dev"]
    if not args.no_tls:
        base += ["certbot", "python3-certbot-nginx"]
    sh("apt-get install -y " + " ".join(base))

    # Node.js 20 LTS via NodeSource if node is missing or too old.
    need_node = True
    if have("node"):
        try:
            out = subprocess.run(["node", "-v"], capture_output=True, text=True).stdout.strip()
            major = int(out.lstrip("v").split(".")[0])
            need_node = major < 18
        except Exception:
            need_node = True
    if need_node:
        info("Installing Node.js 20 LTS (NodeSource)…")
        sh("curl -fsSL https://deb.nodesource.com/setup_20.x | bash -")
        sh("apt-get install -y nodejs")

    for svc in ("rabbitmq-server", "nginx"):
        sh(f"systemctl enable --now {svc}", check=False)
    if args.db == "postgres":
        sh("systemctl enable --now postgresql", check=False)


# ─── PostgreSQL ─────────────────────────────────────────────────────────────
def psql(sql: str, *, db: str = "postgres", capture: bool = False) -> subprocess.CompletedProcess:
    return run(["sudo", "-u", "postgres", "psql", "-d", db, "-tAc", sql], capture=capture, check=False)


def setup_postgres(existing: dict[str, str]) -> str:
    # Reuse the password from an existing .env so re-runs stay consistent.
    pw = None
    cur = existing.get("database_url", "")
    m = re.search(r"//[^:]+:([^@]+)@", cur)
    if m:
        pw = m.group(1)
    pw = pw or secrets.token_urlsafe(18)

    role_exists = (psql("SELECT 1 FROM pg_roles WHERE rolname='alink'", capture=True).stdout or "").strip() == "1"
    if role_exists:
        psql(f"ALTER ROLE alink WITH LOGIN PASSWORD '{pw}'")
    else:
        psql(f"CREATE ROLE alink WITH LOGIN PASSWORD '{pw}'")
    db_exists = (psql("SELECT 1 FROM pg_database WHERE datname='alink'", capture=True).stdout or "").strip() == "1"
    if not db_exists:
        psql("CREATE DATABASE alink OWNER alink")
    psql("GRANT ALL PRIVILEGES ON DATABASE alink TO alink")
    info("PostgreSQL role + database 'alink' ready.")
    return f"postgresql+psycopg2://alink:{pw}@127.0.0.1:5432/alink"


# ─── RabbitMQ ───────────────────────────────────────────────────────────────
def setup_rabbitmq(existing: dict[str, str]) -> str:
    pw = None
    m = re.search(r"//[^:]+:([^@]+)@", existing.get("rabbitmq_url", ""))
    if m:
        pw = m.group(1)
    pw = pw or secrets.token_urlsafe(18)
    vhost = "alink"

    sh("systemctl enable --now rabbitmq-server", check=False)
    sh(f"rabbitmqctl add_vhost {vhost}", check=False)
    users = (run(["rabbitmqctl", "list_users", "-q"], capture=True, check=False).stdout or "")
    if re.search(r"^alink\b", users, re.MULTILINE):
        sh(f"rabbitmqctl change_password alink '{pw}'", check=False)
    else:
        sh(f"rabbitmqctl add_user alink '{pw}'", check=False)
    sh(f'rabbitmqctl set_permissions -p {vhost} alink ".*" ".*" ".*"', check=False)
    info("RabbitMQ vhost + user 'alink' ready.")
    return f"amqp://alink:{pw}@127.0.0.1:5672/{vhost}"


# ─── Backend venv ───────────────────────────────────────────────────────────
def setup_backend(user: str) -> None:
    if not VENV_PY.exists():
        info("Creating backend virtualenv…")
        run(["python3", "-m", "venv", str(VENV)], user=user)
    run([str(VENV_PY), "-m", "pip", "install", "--upgrade", "pip", "wheel"], user=user)
    run([str(VENV_PY), "-m", "pip", "install", "-r", str(BACKEND / "requirements.txt")], user=user)


def init_database(reset: bool, user: str) -> None:
    code = (
        "from app.database import Base, engine; import app.models; "
        + ("Base.metadata.drop_all(bind=engine); " if reset else "")
        + "Base.metadata.create_all(bind=engine); "
        "from app.seed import seed_if_empty; print('seeded' if seed_if_empty() else 'db-ready')"
    )
    run([str(VENV_PY), "-c", code], cwd=BACKEND, user=user)


# ─── Frontend build ─────────────────────────────────────────────────────────
def build_frontend(domain: str, user: str) -> None:
    env = dict(os.environ)
    env["VITE_API_URL"] = f"https://{domain}/api"
    info(f"Building frontend with VITE_API_URL={env['VITE_API_URL']}")
    npm = shutil.which("npm") or "npm"
    if (FRONTEND / "package-lock.json").exists():
        run([npm, "ci"], cwd=FRONTEND, user=user, env=env, check=False)
    if not (FRONTEND / "node_modules").exists():
        run([npm, "install"], cwd=FRONTEND, user=user, env=env)
    run([npm, "run", "build"], cwd=FRONTEND, user=user, env=env)
    if not (DIST / "index.html").exists():
        die("Frontend build did not produce dist/index.html")


# ─── nginx ──────────────────────────────────────────────────────────────────
NGINX_TEMPLATE = """\
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

    client_max_body_size 12m;
    root {dist};
    index index.html;

    # API → FastAPI (the trailing slash on proxy_pass strips the /api prefix)
    location /api/ {{
        proxy_pass http://{api_bind}/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}

    # Uploaded files served by the backend
    location /static/ {{
        proxy_pass http://{api_bind}/static/;
        proxy_set_header Host $host;
    }}

    # SPA history fallback
    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def setup_nginx(domain: str) -> None:
    conf = NGINX_TEMPLATE.format(domain=domain, dist=str(DIST), api_bind=API_BIND)
    avail = Path("/etc/nginx/sites-available/alink")
    enabled = Path("/etc/nginx/sites-enabled/alink")
    avail.write_text(conf, encoding="utf-8")
    if enabled.exists() or enabled.is_symlink():
        enabled.unlink()
    enabled.symlink_to(avail)
    default = Path("/etc/nginx/sites-enabled/default")
    if default.exists() or default.is_symlink():
        default.unlink()
    sh("nginx -t")
    sh("systemctl reload nginx")
    info("nginx configured.")


# ─── systemd ────────────────────────────────────────────────────────────────
API_UNIT = """\
[Unit]
Description=ALink API (gunicorn/uvicorn)
After=network.target postgresql.service rabbitmq-server.service

[Service]
Type=simple
User={user}
Group={group}
WorkingDirectory={backend}
ExecStart={bin}/gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind {api_bind} --workers 2 --timeout 60
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
"""

WORKER_UNIT = """\
[Unit]
Description=ALink {desc} worker
After=network.target postgresql.service rabbitmq-server.service alink-api.service

[Service]
Type=simple
User={user}
Group={group}
WorkingDirectory={backend}
ExecStart={py} -m app.workers.{module}
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
"""

WORKERS = {
    "alink-worker-notifications": ("notifications", "notifications_worker"),
    "alink-worker-ai": ("AI assistant", "ai_worker"),
    "alink-worker-achievements": ("achievements", "achievements_worker"),
}


def setup_systemd(user: str) -> None:
    try:
        group = grp.getgrgid(pwd.getpwnam(user).pw_gid).gr_name
    except KeyError:
        group = user
    units = Path("/etc/systemd/system")
    (units / "alink-api.service").write_text(
        API_UNIT.format(user=user, group=group, backend=str(BACKEND), bin=str(VENV_BIN), api_bind=API_BIND),
        encoding="utf-8",
    )
    for svc, (desc, module) in WORKERS.items():
        (units / f"{svc}.service").write_text(
            WORKER_UNIT.format(desc=desc, module=module, user=user, group=group,
                               backend=str(BACKEND), py=str(VENV_PY)),
            encoding="utf-8",
        )
    sh("systemctl daemon-reload")
    for svc in SERVICES:
        sh(f"systemctl enable {svc}", check=False)
        sh(f"systemctl restart {svc}", check=False)
    info("systemd services installed and (re)started.")


# ─── TLS ────────────────────────────────────────────────────────────────────
def setup_tls(domain: str, email: str | None, no_tls: bool) -> bool:
    if no_tls:
        info("Skipping TLS (--no-tls). Serving plain HTTP on :80.")
        return False
    if not have("certbot"):
        warn("certbot not installed; skipping TLS.")
        return False
    email_args = ["-m", email] if email else ["--register-unsafely-without-email"]
    res = run(
        ["certbot", "--nginx", "-d", domain, "--non-interactive", "--agree-tos",
         "--redirect", *email_args],
        check=False,
    )
    if res.returncode == 0:
        info(f"HTTPS enabled for {domain}.")
        return True
    warn("certbot failed (is the DNS A record for the domain pointing at this VM?). Serving HTTP for now.")
    return False


# ─── Health summary ─────────────────────────────────────────────────────────
def health_summary(domain: str, https: bool) -> None:
    info("Service status:")
    for svc in SERVICES + ["nginx", "rabbitmq-server"]:
        sh(f"systemctl is-active {svc} | sed 's/^/  {svc}: /'", check=False)
    try:
        with urllib.request.urlopen(f"http://{API_BIND}/health", timeout=5) as r:
            info(f"Local API /health: {r.status} {r.read().decode()[:80]}")
    except Exception as exc:
        warn(f"Local API health check failed: {exc}")
    scheme = "https" if https else "http"
    print()
    info(f"Done. ALink should be live at {scheme}://{domain}")
    info(f"  • API docs:    {scheme}://{domain}/api/docs")
    info(f"  • Demo logins: student@alink.app / alumni@alink.app / admin@alink.app  (password123)")


# ─── Main ───────────────────────────────────────────────────────────────────
def main() -> int:
    parser = argparse.ArgumentParser(description="Deploy ALink natively on a GCP VM.")
    parser.add_argument("--domain", default=DEFAULT_DOMAIN)
    parser.add_argument("--email", default=os.environ.get("CERTBOT_EMAIL"))
    parser.add_argument("--db", choices=["postgres", "sqlite"], default="postgres")
    parser.add_argument("--no-tls", action="store_true")
    parser.add_argument("--skip-system", action="store_true")
    parser.add_argument("--reset-db", action="store_true")
    parser.add_argument("--branch", default="main", help="informational only")
    args = parser.parse_args()

    require_root()
    user = deploy_user()
    info(f"Deploying ALink from {ROOT} as service user '{user}' (domain: {args.domain}, db: {args.db}).")

    install_system(args)

    existing = read_env()
    db_url = setup_postgres(existing) if args.db == "postgres" else "sqlite:///./alink.db"
    rabbit_url = setup_rabbitmq(existing)

    env_values = {
        "database_url": db_url,
        "rabbitmq_url": rabbit_url,
        "events_exchange": existing.get("events_exchange", "alink.events"),
        "jwt_secret": existing.get("jwt_secret") or secrets.token_urlsafe(48),
        "jwt_algorithm": existing.get("jwt_algorithm", "HS256"),
        "jwt_expires_minutes": existing.get("jwt_expires_minutes", "10080"),
        "cors_origins": f"https://{args.domain}",
        "anthropic_api_key": existing.get("anthropic_api_key") or os.environ.get("ANTHROPIC_API_KEY", ""),
        "anthropic_model": existing.get("anthropic_model", "claude-haiku-4-5"),
    }
    write_env(env_values, user)

    setup_backend(user)
    init_database(args.reset_db, user)
    build_frontend(args.domain, user)

    setup_nginx(args.domain)
    setup_systemd(user)
    https = setup_tls(args.domain, args.email, args.no_tls)

    health_summary(args.domain, https)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
